name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  merge_group:
    types: [checks_requested]
  schedule:
    # Runs at 02:30, every Saturday
    - cron: "30 2 * * 6"
    
    
jobs:
  Test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - { target: aarch64-apple-darwin, os: macos-14 }
          - { target: x86_64-apple-darwin, os: macos-13 }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: aarch64-unknown-linux-gnu, os: ubuntu-latest }
          - { target: x86_64-pc-windows-msvc, os: windows-latest }
    runs-on: ${{ matrix.platform.os }}
    env:
      HARFBUZZ_SYS_NO_PKG_CONFIG: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          profile: minimal

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1-mesa-dev libgtk-3-dev libsdl2-dev cmake
        
      - name: Install rustc target
        run: rustup target add aarch64-unknown-linux-gnu
        
      - name: Build arm64 simd
        run: cargo build --target aarch64-unknown-linux-gnu
        working-directory: simd

      - name: Build arm64 geometry
        run: cargo build --target aarch64-unknown-linux-gnu
        working-directory: geometry

      - name: Build
        run: cargo build

      - name: Test
        run: cargo test

  build_result:
    name: Result
    runs-on: ubuntu-latest
    needs:
      - "Test"
    steps:
      - name: Mark the job as successful
        run: exit 0
        if: success()
      - name: Mark the job as unsuccessful
        run: exit 1
        if: "!success()"
